name: boilerplate-prod

services:
  boilerplate-server:
    build:
      context: .
      dockerfile: Dockerfile.production
    restart: always
    env_file:
      - path: ./.env
        required: false
    ports:
      - 5050:5050
